### ISSUE TITLE
Documentation is poor

### ISSUE THREAD

**Issue by mohammedSlimani** [e-mobadara/2d-game-lib#1]
We need to document the code and The functionalities of the library to make it easy for others to understand it well.

**Comment by mohammedSlimani** [comment]
I started working on the javadoc and the Wiki of the Repo

**Comment by MarouaneMORCHID** [comment]
I got you Man , im working on a fix rite no

**Comment by mohammedSlimani** [comment]
I have added JavaDoc to most of the classes. and Made a walk-through Documentation at https://e-mobadara.github.io/ 
It should be enough for now!
