### ISSUE TITLE
draging problem

### ISSUE THREAD

**Issue by ghost** [e-mobadara/2d-game-lib#6]
while dragging a sprite it keeps repeating the image.
any ideas !?

**Comment by mohammedSlimani** [comment]
Hey Mouatta1, You can hack around this "unwanted" behaviour by drawing a colour in your render method in your screen. 
Add this lines in your render method:
```
        Graphics g = game.getGraphics();
        g.drawARGB(255, 0, 0, 0);
```
Your sprites are still going to draw normal.

**Comment by mohammedSlimani** [comment]
Note that if you are using a sprite as a background, which you probably should be using, then you wont have this problem.
