### ISSUE TITLE
The new version 1.2.3

### ISSUE THREAD

**Issue by mahdimouatta** [e-mobadara/2d-game-lib#8]
some methods  changed in the new version( such as the sprite and the bouttonUI contructors)  which i guess shouldn't, so should i proceed with the new version and make the necessary changes or keep working with the old 1.

**Comment by mohammedSlimani** [comment]
After a revision of the implementation, We have seen that Sprite doesn't need a game object. It was just redundant. Which means when you define your sprite you dont need to have the super() method in the constructor to call the game object. So, You can just remove the game object from super() and you can keep your code intact.
